name: Run Python Script Daily

on:
  schedule:
    - cron: '0 2 * * *'  # This runs at 02:00 UTC every day
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install requests
        #pip install json
        pip install pandas
        pip install datetime

    - name: Run Python script
      run: python weather.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add processed_weather_data.json
        git commit -m 'Update JSON data'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: processed_weather_data.json
